igl: Tesselation
Tesselation
IGL - Interactive Graphics Library
Classes
struct EdgeHashTable
Hashtable for edges as pair of indices (allows to quickly lookup edge index by vertex indices)
shape tesselate interface
Shape * tesselate_shape (Shape *shape, int level, bool smooth)
Tesselate Shape the given number of times.
tesselation interface
void primitive_tesselation_init (Primitive *prim, bool override=false, int override_level=0, bool override_smooth=false)
void primitives_tesselation_init (PrimitiveGroup *prim, bool override=false, int override_level=0, bool override_smooth=false)
void shape_tesselation_init (Shape *shape, bool override=false, int override_level=0, bool override_smooth=false)
void scene_tesselation_init (Scene *scene, bool override=false, int override_level=0, bool override_smooth=false)
Function Documentation
Shape* tesselate_shape (Shape * shape, int level, bool smooth)
Tesselate Shape the given number of times.
Parameters:
shape The Shape to tesselate
level The number of times to tesselate
smooth Determines whether the tesselated mesh will have smoothed normals
Returns:
The tesselated shape
References _tesselate_catmullclark_once(), _tesselate_mesh_once(), _tesselate_shape_uniform(), _tesselate_subdiv_once(), EdgeHashTable::edges, not_implemented_error(), put_your_code_here(), and tesselate_shape().
Referenced by tesselate_shape().