igl: src/igl/tesselate.cpp File Reference
src/igl/tesselate.cpp File Reference
IGL - Interactive Graphics Library
Tesselation.
Functions
Shape * _tesselate_shape_uniform (const function< frame3f(const vec2f &)> shape_frame, int ur, int vr, bool ccw, bool smooth)
Tesselate parametric Shape (two parameters)
Shape * _tesselate_shape_uniform (const function< frame3f(const vec2f &)> shape_frame, int ur, int vr, int ul, int vl, bool ccw, bool smooth)
Tesselate Shape (uniformly) with lines.
Shape * _tesselate_shape_uniform (const function< frame3f(float)> shape_frame, const function< float(float)> shape_radius, int ur, bool smooth)
Tesselate parametric Shape (one parameter) that has a radius. ex: bezier spline.
LineSet * _tesselate_lineset_once (LineSet *lines)
TriangleMesh * _tesselate_trianglemesh_once (TriangleMesh *mesh)
Mesh * _tesselate_mesh_once (Mesh *mesh)
Tesselate Mesh one time.
CatmullClarkSubdiv * _tesselate_catmullclark_once (CatmullClarkSubdiv *subdiv)
Apply Catmull-Clark subdivision surface rules on subdiv.
Subdiv * _tesselate_subdiv_once (Subdiv *subdiv)
Apply subdivision surface rules on subdiv.
Shape * _tesselate_recursive (const function< Shape *(Shape *)> &tesselate_once, Shape *tesselation, int level, bool smooth, const function< Shape *(Shape *)> &to_mesh=function< Shape *(Shape *)>())
Shape * tesselate_shape (Shape *shape, int level, bool smooth)
Tesselate Shape the given number of times.
void shape_tesselation_init (Shape *shape, bool override, int override_level, bool override_smooth)
void primitive_tesselation_init (Primitive *prim, bool override, int override_level, bool override_smooth)
void primitives_tesselation_init (PrimitiveGroup *group, bool override, int override_level, bool override_smooth)
void scene_tesselation_init (Scene *scene, bool override, int override_level, bool override_smooth)
Detailed Description
Tesselation.
Function Documentation
CatmullClarkSubdiv* _tesselate_catmullclark_once (CatmullClarkSubdiv * subdiv)
Apply Catmull-Clark subdivision surface rules on subdiv.
Parameters:
subdiv The mesh to subdivide
Returns:
The subdivided mesh
References put_your_code_here().
Referenced by tesselate_shape().
Mesh* _tesselate_mesh_once (Mesh * mesh)
Tesselate Mesh one time.
Parameters:
mesh The Mesh to tesselate
Returns:
The tesselated Mesh
References put_your_code_here().
Referenced by tesselate_shape().
Shape* _tesselate_shape_uniform (const function< frame3f(const vec2f &)> shape_frame, int ur, int vr, bool ccw, bool smooth)
Tesselate parametric Shape (two parameters)
Parameters:
shape_frame Function that returns the frame of the Shape at the given vec2f coordinate
ur Number of divisions along first parameter
vr Number of divisions along second parameter
ccw Specifies whether faces are to be generated counter-clockwise or clockwise
smooth Specifies whether the tesselated surface is to have smooth normals
Returns:
The tesselated shape
Referenced by _tesselate_shape_uniform(), and tesselate_shape().
Shape* _tesselate_shape_uniform (const function< frame3f(const vec2f &)> shape_frame, int ur, int vr, int ul, int vl, bool ccw, bool smooth)
Tesselate Shape (uniformly) with lines.
Parameters:
shape_frame Function that returns the frame of the Shape at the given vec2f coordinate
ur Number of divisions along first parameter for Shape
vr Number of divisions along second parameter for shape
ul Number of divisions along first parameter for lines
vl Number of divisions along second parameter for lines
ccw Specifies whether faces are to be generated counter-clockwise or clockwise
smooth Specifies whether the tesselated surface is to have smooth normals
Returns:
The tesselated shape with lines
References _tesselate_shape_uniform().
Shape* _tesselate_shape_uniform (const function< frame3f(float)> shape_frame, const function< float(float)> shape_radius, int ur, bool smooth)
Tesselate parametric Shape (one parameter) that has a radius. ex: bezier spline.
Parameters:
shape_frame Function that returns the frame of Shape at the given single float coordinate
shape_radius Function that returns the radius of Shape at the given coordinate
ur Number of divisions along parameter
smooth Specifies whether the tesselated surface is to have smooth normals
Returns:
The tesselated Shape
References put_your_code_here().
Subdiv* _tesselate_subdiv_once (Subdiv * subdiv)
Apply subdivision surface rules on subdiv.
Parameters:
subdiv The mesh to subdivide
Returns:
The subdivided mesh
References Subdiv::_tesselation_lines, Subdiv::crease_edge, Subdiv::crease_vertex, pi, Subdiv::pos, Subdiv::quad, range(), Subdiv::texcoord, and Subdiv::triangle.
Referenced by tesselate_shape().